# Generated by Django 5.1.1 on 2024-10-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='BlogTag',
        ),
    ]
