# Generated by Django 5.1.1 on 2024-10-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_rename_tag_blogtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
